// flow-typed signature: 45977444ad45eb47b1b52e4489478023
// flow-typed version: <<STUB>>/imask_v^3.4.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imask'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imask' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'imask/dist/imask.es' {
  declare module.exports: any;
}

declare module 'imask/dist/imask.es.min' {
  declare module.exports: any;
}

declare module 'imask/dist/imask' {
  declare module.exports: any;
}

declare module 'imask/dist/imask.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'imask/dist/imask.es.js' {
  declare module.exports: $Exports<'imask/dist/imask.es'>;
}
declare module 'imask/dist/imask.es.min.js' {
  declare module.exports: $Exports<'imask/dist/imask.es.min'>;
}
declare module 'imask/dist/imask.js' {
  declare module.exports: $Exports<'imask/dist/imask'>;
}
declare module 'imask/dist/imask.min.js' {
  declare module.exports: $Exports<'imask/dist/imask.min'>;
}
