// flow-typed signature: a9e6651f099c7435104bd55b85064f70
// flow-typed version: <<STUB>>/react-maskedinput_v^4.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-maskedinput'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-maskedinput' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-maskedinput/es/index' {
  declare module.exports: any;
}

declare module 'react-maskedinput/lib/index' {
  declare module.exports: any;
}

declare module 'react-maskedinput/umd/react-maskedinput' {
  declare module.exports: any;
}

declare module 'react-maskedinput/umd/react-maskedinput.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-maskedinput/es/index.js' {
  declare module.exports: $Exports<'react-maskedinput/es/index'>;
}
declare module 'react-maskedinput/lib/index.js' {
  declare module.exports: $Exports<'react-maskedinput/lib/index'>;
}
declare module 'react-maskedinput/umd/react-maskedinput.js' {
  declare module.exports: $Exports<'react-maskedinput/umd/react-maskedinput'>;
}
declare module 'react-maskedinput/umd/react-maskedinput.min.js' {
  declare module.exports: $Exports<'react-maskedinput/umd/react-maskedinput.min'>;
}
