// flow-typed signature: d27c9697e76a66abdfac42e0118d8980
// flow-typed version: <<STUB>>/react-responsive-modal_v^3.3.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive-modal/lib/index.es' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/lib/index' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/src/close-icon' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/src/index' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/src/modal-manager' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/src/modal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive-modal/lib/index.es.js' {
  declare module.exports: $Exports<'react-responsive-modal/lib/index.es'>;
}
declare module 'react-responsive-modal/lib/index.js' {
  declare module.exports: $Exports<'react-responsive-modal/lib/index'>;
}
declare module 'react-responsive-modal/src/close-icon.js' {
  declare module.exports: $Exports<'react-responsive-modal/src/close-icon'>;
}
declare module 'react-responsive-modal/src/index.js' {
  declare module.exports: $Exports<'react-responsive-modal/src/index'>;
}
declare module 'react-responsive-modal/src/modal-manager.js' {
  declare module.exports: $Exports<'react-responsive-modal/src/modal-manager'>;
}
declare module 'react-responsive-modal/src/modal.js' {
  declare module.exports: $Exports<'react-responsive-modal/src/modal'>;
}
