// flow-typed signature: 5440c534976d681e7a353e8177e2907d
// flow-typed version: <<STUB>>/text-mask-addons_v^3.8.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text-mask-addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'text-mask-addons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'text-mask-addons/dist/createAutoCorrectedDatePipe' {
  declare module.exports: any;
}

declare module 'text-mask-addons/dist/createNumberMask' {
  declare module.exports: any;
}

declare module 'text-mask-addons/dist/emailMask' {
  declare module.exports: any;
}

declare module 'text-mask-addons/dist/textMaskAddons' {
  declare module.exports: any;
}

declare module 'text-mask-addons/src/createAutoCorrectedDatePipe' {
  declare module.exports: any;
}

declare module 'text-mask-addons/src/createNumberMask' {
  declare module.exports: any;
}

declare module 'text-mask-addons/src/emailMask' {
  declare module.exports: any;
}

declare module 'text-mask-addons/src/emailPipe' {
  declare module.exports: any;
}

declare module 'text-mask-addons/src/index' {
  declare module.exports: any;
}

declare module 'text-mask-addons/test/addonsBundle.spec' {
  declare module.exports: any;
}

declare module 'text-mask-addons/test/createAutoCorrectedDatePipe.spec' {
  declare module.exports: any;
}

declare module 'text-mask-addons/test/createNumberMask.spec' {
  declare module.exports: any;
}

declare module 'text-mask-addons/test/emailMask.spec' {
  declare module.exports: any;
}

declare module 'text-mask-addons/webpack.buildAddons' {
  declare module.exports: any;
}

// Filename aliases
declare module 'text-mask-addons/dist/createAutoCorrectedDatePipe.js' {
  declare module.exports: $Exports<'text-mask-addons/dist/createAutoCorrectedDatePipe'>;
}
declare module 'text-mask-addons/dist/createNumberMask.js' {
  declare module.exports: $Exports<'text-mask-addons/dist/createNumberMask'>;
}
declare module 'text-mask-addons/dist/emailMask.js' {
  declare module.exports: $Exports<'text-mask-addons/dist/emailMask'>;
}
declare module 'text-mask-addons/dist/textMaskAddons.js' {
  declare module.exports: $Exports<'text-mask-addons/dist/textMaskAddons'>;
}
declare module 'text-mask-addons/src/createAutoCorrectedDatePipe.js' {
  declare module.exports: $Exports<'text-mask-addons/src/createAutoCorrectedDatePipe'>;
}
declare module 'text-mask-addons/src/createNumberMask.js' {
  declare module.exports: $Exports<'text-mask-addons/src/createNumberMask'>;
}
declare module 'text-mask-addons/src/emailMask.js' {
  declare module.exports: $Exports<'text-mask-addons/src/emailMask'>;
}
declare module 'text-mask-addons/src/emailPipe.js' {
  declare module.exports: $Exports<'text-mask-addons/src/emailPipe'>;
}
declare module 'text-mask-addons/src/index.js' {
  declare module.exports: $Exports<'text-mask-addons/src/index'>;
}
declare module 'text-mask-addons/test/addonsBundle.spec.js' {
  declare module.exports: $Exports<'text-mask-addons/test/addonsBundle.spec'>;
}
declare module 'text-mask-addons/test/createAutoCorrectedDatePipe.spec.js' {
  declare module.exports: $Exports<'text-mask-addons/test/createAutoCorrectedDatePipe.spec'>;
}
declare module 'text-mask-addons/test/createNumberMask.spec.js' {
  declare module.exports: $Exports<'text-mask-addons/test/createNumberMask.spec'>;
}
declare module 'text-mask-addons/test/emailMask.spec.js' {
  declare module.exports: $Exports<'text-mask-addons/test/emailMask.spec'>;
}
declare module 'text-mask-addons/webpack.buildAddons.js' {
  declare module.exports: $Exports<'text-mask-addons/webpack.buildAddons'>;
}
